version: '3.1'

services:
  client:
    build: .
    restart: always
    volumes:
      - ./client:/home/node/app
      - ./shared:/home/node/shared
    ports:
      - 3000:3000

  server:
    build: .
    restart: always
    volumes:
      - ./server:/home/node/app
      - ./shared:/home/node/shared
    ports:
      - 5000:5000

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
